### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sdfww** [yp05327/BaiduCloudHelper#2]
.

**Comment by yp05327** [comment]
response.content改成response.text试试

**Comment by sdfww** [comment]
?
这个Body是不是是不是二进制格式，而且这个请求的结果也是和Body类似的内容，有办法将其解码吗？

`HTTP/1.1 200 OK
Cache-Control:	no-cache
Connection:	keep-alive
Content-Type:	text/html
Date:	Sun, 24 Feb 2019 19:15:46 GMT
Flow-Level:	3
Logid:	
P3p:	CP=" OTI DSP COR IVA OUR IND COM "
Server:	nginx
Set-Cookie:	BAIDUID=; expires=Mon, 24-Feb-20 19:15:46 GMT; max-age=31536000; path=/; domain=.baidu.com; version=1
Vary:	Accept-Encoding
X-Bcsp2p-Remote-Ip:	10.26.38.44
X-Powered-By:	BaiduCloud
Yld:	125836990493715671
Yme:	ZIGW/iYrV0kMajAYTmvhqGlXv/MATgb/qABOw4ipWw==
Transfer-Encoding:	chunked`

**Comment by yp05327** [comment]
比如你用的如果是类似于这样的语句获得的response 
response = self.session.post(url, data=post_data, headers=req_headers)
如果用
response.content
读取，如果内容中有编码内容就会得到类似你这样的结果。因为他获取的是byte型数据，需要进行解码
然后这种情况需要使用
response.text
读取，返回的是string，就可以看到decode之后的内容了

然后，你说的body是post时候发出请求中的body也就是post data，还是response中的body

**Comment by sdfww** [comment]
是POST Data

**Comment by yp05327** [comment]
你这是直接拉的网盘客户端的包吧

**Comment by sdfww** [comment]
是抓包抓到的

**Comment by yp05327** [comment]
无解

**Comment by sdfww** [comment]
这是二进制编码吗？

**Comment by yp05327** [comment]
编码指的是用一个有规律二进制数来对应某一个字符
加密指的是把信息通过数学计算变成没有规律的二进制数
当然也有些早期加密方式和编码相同，但是现代加密方式大都是数学计算，这里的加密指的是现代加密方式
编码是有规律的，加密是没规律的
我认为这是一个经过现代加密算法后产生的二进制序列，可能还加了点别的东西
即，我觉得不是二进制编码

而且这是app发送的请求包，做个加密太容易了，如果是网页端用的js加密，那破解就很容易了，因为加密代码你都看得到

**Comment by yp05327** [comment]
以前拿客户端试过试用加速的原理，结果是客户端会发送一个类似你这样的一个认证请求，然后再发送获取下载url的请求，这时候获得的链接就和正常下载的不一样，是不限速的，但是这样的链接一天只能获取3次。但是现在这个接口改掉了，我也懒得弄新的是啥了，普通的链接可以做到大概几M/s的速度了，弄那个也没啥意思，与其花时间在这上面还不如干点别的

**Comment by sdfww** [comment]
如果是加密了，那这个请求或许有关

POST http://nj.t.bcsp2p.baidu.com/seed HTTP/1.1
Content-Length:	128
Host:	nj.t.bcsp2p.baidu.com
\xc2\x9a\x1dT\\r\xedo\x00\x10\x00\x08\x01\x00\x00\x02\x02\x00\x15\x00o\xedr\\3\x00\x00\x00\x00\x00\x00`\xf8\xc1.K\xd3]\xea\xf9\xb54\xae'\xf8\x85;i\x9dl" \x04u{)\x84\xfb\xe6I\x86\xdf\x9a\xaa\x1b\x93\xedd,\xe5Wq\xdaW\xb1\x9f\x1c\xb9\x91Y\xaee\xaa\xda6\x8d\xb9K\xb7\x9c\xc1kUl\x08-&\xfc\xa5
\xa6^S
$J\x19A\x80=\xca[\x07\x1a\xe5\xb4U\x12\xe6\xcfL6\x08\xe1j\x8dQ\xad

0000000000 c2 9a 1d 54 5c 72 ed 6f 00 10 00 08 01 00 00 02   ...T\r.o........
0000000010 02 00 15 00 6f ed 72 5c 33 00 00 00 00 00 00 60   ....o.r\3......`
0000000020 f8 c1 2e 4b d3 5d ea f9 b5 34 ae 27 f8 85 3b 69   ...K.]...4.'..;i
0000000030 9d 6c 22 20 04 75 7b 29 84 fb e6 49 86 df 9a aa   .l" .u{)...I....
0000000040 1b 93 ed 64 2c e5 57 71 da 57 b1 9f 1c b9 91 59   ...d,.Wq.W.....Y
0000000050 ae 65 aa da 36 8d b9 4b b7 9c c1 6b 55 6c 08 2d   .e..6..K...kUl.-
0000000060 26 fc a5 0d a6 5e 53 0d 24 4a 19 41 80 3d ca 5b   &....^S.$J.A.=.[
0000000070 07 1a e5 b4 55 12 e6 cf 4c 36 08 e1 6a 8d 51 ad   ....U...L6..j.Q.

这是熵

**Comment by sdfww** [comment]
你是怎么试试用加速的？

**Comment by sdfww** [comment]
什么认证请求，你怎么看到的？
