### ISSUE TITLE
还可以登录吗？

### ISSUE THREAD

**Issue by sdfww** [yp05327/BaiduCloudHelper#3]
我在Windows上没有成功，说要导入baiducloudengine模块，我也不知道怎么弄。

**Comment by yp05327** [comment]
我本地跑了一下是可以登录的，没跑成功的详细错误信息，以及clone的项目文件的目录列表的可以发一下吗。“要导入baiducloudengine模块”的错误描述不太清楚是发生了什么。

err_no=7不一定就是密码字段错了，其他字段也会导致。比如发送登陆请求时还需要填写rsakey字段，如果这个字段为空，也会导致err_no=7

至于算法是否等价的问题，这个加密库是别人写的，具体不是太清楚。个人觉得应该是等价的。
具体可以去该库的官方项目地址询问：
https://launchpad.net/pycrypto/

**Comment by sdfww** [comment]
`r>python main.py -w
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from baiducloudengine import BaiduCloudEngine
ModuleNotFoundError: No module named 'baiducloudengine'`

就是这个提示，Windows CMD下。我是从https://github.com/yp05327/BaiduCloudHelper/archive/master.zip
下载的。


我猜也是，Body的其他参数错了，也可能会是err_no=7。可我想不出除了password，还有其他参数是错的。

token                获取的，不可能错
tt                       时间戳，不可能错
codestring        获取的且不需要验证码，不可能错
gid                    生成的，不可能错
username         不可能是错的
password          不能保证加密算法正确，非常可疑
rsakey               获取的，不可能错
ppui_logintime  时间差，随意修改，不可能错
ds                      用了一个固定值，ds实际是使用fs参数获取的，而fs是个随机值，函数很复杂，所以将ds用了抓取的一个值
tk                       获取的，不可能错
dv                      用了一个固定值，dv实际是函数生成的随机值，函数太复杂，同样用了一个抓取的值
traceid               生成的，不可能错
callback             生成的，不可能错


除了 ds、dv 不是从js翻译而来外，其他的几个都翻译了，剩下的全是固定值，除了password要加密外。
并且 ds、dv 实际上也是随机值，我觉得不太可能错在这。
所以剩下的只有password了。


`staticpage=https%3A%2F%2Fpan.baidu.com%2Fres%2Fstatic%2Fthirdparty%2Fpass_v3_jump.html
&charset=UTF-8
&token=0d6550cc08343a056cc923ed1ab2f8f9
&tpl=netdisk
&subpro=netdisk_web
&apiver=v3
&tt=1558962719991
&codestring=
&safeflg=0
&u=https%3A%2F%2Fpan.baidu.com%2Fdisk%2Fhome
&isPhone=
&detect=1
&gid=272373F-6440-4454-95FA-BD32CAEA7A94
&quick_user=0
&logintype=basicLogin
&logLoginType=pc_loginBasic
&idc=
&loginmerge=true
&username=此处已略去
&password=SQ1NyGtRtK56%2B%2F66sUXbz7DJHAYKYMGQZ6L%2BCNEaABtvPLRTHTdHNNZk0P9yQOAov2r2SMeI9UDbY7GSNDVV4QBaGkGDzCZs%2F3AZMb7FUS0CIHPi35rSptD0XtutXxuPfrrlXO8Wy7nbQydovekPkAtneCxBPh1U4bcNzcs2wVg%3D
&mem_pass=on
&rsakey=EPm2E8GcltFpcztQcGGD16ZJnTO3FQKX
&crypttype=12
&ppui_logintime=5000
&countrycode=
&fp_uid=
&fp_info=
&loginversion=v4
&ds=izoeVBby1yMDPPgyxgmY1kwcGWDUOoQKY2z%2FCgy7HduAf8l3ajXSqTa5k%2FPavtEk4z5%2BGitdfE2Eo9jNhRjydhC19FNNPf3PLuLYK%2F1AZO9O927TmqQx%2FotppdnCLNk%2FGox8QaXYJLhwiWvLBJSZqz2vHb6kmU5NWjRfN9YPbxs3mvH3FJJQVNZ0Fic12BzHeAnv3EoLadkt6pcBvGjt9a%2B2DhhIBQZtdWrp%2B0NaaaP6p3z57iB1ynVw%2FS57udn3dvPeHD6W2oeQgt0tBD3NnyKva40rRGWSZXgjkzqUVd%2BBiWBVWrmNUSknSFLR9OZ8gjdvw5PqdhGzfB6Y0CD7EiCgpw6Ah1qprLG7i%2BjTo8CZQWFN1kCgBWf2wPlocujKfAv9cVunlVeVFOJHCeoE7aLqEEQLf1ziX2GcMuEvh%2FPRMR3Qi7QdEEOxatRyJYLbJbFuQV%2BOo3xV9KyYLmjU78xwcxbUMtjfRw%2FowJjaYxsA3eSs8wjMdkxUQ3U2edt55SgYInDR71uG6%2Fh%2FbF042oN4Kmx80ViyuzxB1sjC7P7JnVk9dzQD%2FBpgbaHrJ%2FXBag9zEd7QTU%2BL4De0QXJpwmixskaFyGDZudwyErzOg3Z4eT3GxhnfZNHa2Oa%2FJJ4SIRtb%2BXaBELwn%2Fl7pwsimwMu9Cnx%2BveL%2FRtFGFpLjFCnhbP46kq7HltSICsW0xxP7JYpJzP2U9z%2B9zHb9MUL8W79sxDtqT%2FTnWNEHUWe2CAFxClQMt9zMWjrJ8mVrScMb8%2Bp5tySNJaQ%2BePkJ9a27OQ%3D%3D
&tk=pplogid=1993yfZnsBtmizlxak5OVhq%2BKcScgmpSuPgvmPTYKLiPEev6zfpOfv9EY1HCSQsWb0ii
&dv=tk0.101885938623256231558946209747%40llg0pss1CU8mXFEFxuFT2sMiZEFihts2Zt5L6-0HAxEzZTAD%7E-s1Jzsa%7Ew8m%7E%7Ep29hGT5DEFitMihGF2lyMiZzAMrOAa3kIz93pk7jokQytkCzpkqU6n2o9irhG6ZtF2sEMY9tMjA3JL3LPFsRA4FU81Q-sk9lokCU8mXFEFxuFT2sMiZEFihts2Zt5L6-0HAxEzZTAD%7EY8Gny8u%7E_sg0axokJxpkEioD%7EXs1CxsmXFEFxuFT2sMiZEFihts2ZtALZR546-6FXRAz3gEa9gtk7XoD%7EyokqU8GTi8GCUtkTisW%7E-okFU818woGTU6n2o9irhG6ZtF2sEMY9tMjA3JL3LPFsRA46lokQipk8y8m%7EY81Cys-XFEFxuFT2sMiZEFihts2ZtIH6KCL6-F42YJyXVCL6Utkn%7E8GJU8YTXpk8yoG8%7Ep29hGT5DEFitMihGF2lyMiZY5HrK0M9lxhh0ChEV4ddJhEgi8D%7E-pkJywgc54U%7Ep1n%7E8GQwsGTYokC-8Y7is17Y8GFiokTys17%7EoGJys%7E__ige0u9yJu8dp-Z%7ECHwgCL2OAuFgCzZKp-XiIL93AL3gAHE_Bgc8m%7E%7Epkn-81CUsYnipknYs1CUsYCwpknYs1CU8G8zsW%7Ej8YQ_
&traceid=6E972601
&callback=parent.bd__pcbs__wv7b6d
`

**Comment by sdfww** [comment]
手机版的加密方法好像和PC的不一样。

**Comment by yp05327** [comment]
文件目录里main和baiducloudengine放在一起了？

**Comment by sdfww** [comment]
在一起啊，我解压 BaiduCloudHelper-master.zip 得到的，什么都没改。
我用的是 python-3.7.3-embed-amd64.zip 版，莫非是它的问题？
