### ISSUE TITLE
有个问题想不通

### ISSUE THREAD

**Issue by fghex** [yp05327/BaiduCloudHelper#4]
毒是据啥限速地
单纯的下载地址吗
如果是，糊涂了，那现在的不登录又是咋做的，它那服务器上肯定登录了，要是单纯的据地址，那么多人用，它那号早被限了

**Comment by fghex** [comment]
在不啊

**Comment by yp05327** [comment]
刚开始做这个项目的时候 我用的是mac上的网盘客户端抓了下包看了下试用加速的原理
普通的就是向获取链接的api发送一个请求，然后获得的地址就是很多直链提取工具所获得的类似的东西
但是试用加速是向另一个api提交一个申请之后，再向获取链接的api发送一个请求返回和原先完全不一样的下载地址，然后用这个地址下载就不限速，你甚至可以在别的浏览器/下载器里面使用这个链接
但是加速地址是有有效期的 而且试用一天也就2次
现在估计早就变了

**Comment by fghex** [comment]
我理解你说的，但我说的不是这意思
我是说当前的不登录下载方法，就是说会把分享链接发到它们自己的服务器上，它们用它们的账号获取下载地址，之后再返回来。
之前我挂代理应该和这个道理一样，但下十几G后会限速，但他们的不会。我又想了下，它们应该用的是会员账号。
如果是这样，那对自己用就行不通了，买个会员、再弄个服务器...瞎扯了
我在想百毒根据啥限速的，估计从下载地址能查是哪个账号。这样就没办法了。

**Comment by fghex** [comment]
有啥想法吗？毒好像IP+账号一块封

**Comment by yp05327** [comment]
你说的这个能给个链接吗 我看一下

**Comment by yp05327** [comment]
最近有点忙 可能不能及时回 抱歉

**Comment by fghex** [comment]
没有什么链接啊，就是说它是据啥来封的，上面说了用代理获取地址返回，相当于本地没登录，但代理上的号一样被封，那么毒应该可以仅从下载地址里就能知道是哪个id获取的
我发现毒不但会监视ip，而且应该能从下载地址识别id，更狠的是毒那边还能监视流量。前1秒还满速下，流量一超，立刻100K，这明显流量被监视了。被限后换号，新号一下载马上封，这明显ip被监视了。
我猜它能据 id+IP+流量，而且即使不登录，它也能从地址里知道是哪个id，知道id就可限流量，只要没给它钱，一天最多就几个G，好像越来越少。给钱的号也好多被限的，是不是也有流量限制。
虽说换ip换号似乎可以一试，但没给它钱的号好像是绕不开流量这一关。
那个*****wp网页不登录下载几乎是个残废，但是个思路，我猜它用的至少是每月10块钱号。但如果仅一个人用，这种方法就得不偿失了。

**Comment by yp05327** [comment]
下载地址就是账号申请的所以肯定可以追溯到账号
下载ip也是肯定可以监视的
硬件可能也有监视
所以换机器+ip+账号 用断点方法可能可以 但是成本很高，所以现在这东西我觉得已经越来越难弄了偶尔用一下还是没问题的

**Comment by fghex** [comment]
我又看了下下载地址，账号id在里面呢，还不能去掉或瞎写，没办法了。上面说的代理是毫无用处了，而且可以断定那两个免登录的在它们自己服务器上用的定是会员id了。一点办法都没有了。

**Comment by yp05327** [comment]
也就只有这种办法可以了
要么就是我这样拿到普通下载链接 开n个线程去下

**Comment by fghex** [comment]
嗯，这是唯一的一条路了，而开n个线程应该没用了，从B***uPCS-Go的Issues看，似乎已经失效了，不过我没用它测试过。proxy**-down是不是还能用，也不清楚，似乎这两者都是这原理。
